services:
  product:
    image: 'product_app:latest'
    container_name: 'product'
    depends_on:
      - 'product_db'
    ports:
      - '8080:8080'
    environment:
      spring_datasource_url: 'jdbc:postgresql://product_db:5432/product_db'
      spring_datasource_username: 'root'
      spring_datasource_password: 'secret'
      spring_datasource_driver-class-name: 'org.postgresql.Driver'
      spring_jpa_properties_hibernate_dialect: 'org.hibernate.dialect.PostgreSQLDialect'
      spring_jpa_hibernate_ddl-auto: 'create-drop'
      spring_jpa_defer-datasource-initialization: 'true'
      spring_sql_init_mode: 'always'
  product_db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'product_db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'secret'
    ports:
      - '5430:5432'
  cart:
    image: 'cart_app:latest'
    container_name: 'cart'
    depends_on:
      - 'cart_db'
    ports:
      - '8081:8081'
    environment:
      spring_datasource_url: 'jdbc:postgresql://cart_db:5432/cart_db'
      spring_datasource_username: 'root'
      spring_datasource_password: 'secret'
      spring_datasource_driver-class-name: 'org.postgresql.Driver'
      spring_jpa_properties_hibernate_dialect: 'org.hibernate.dialect.PostgreSQLDialect'
      spring_jpa_hibernate_ddl-auto: 'create-drop'
      spring_jpa_defer-datasource-initialization: 'true'
      spring_sql_init_mode: 'always'
  cart_db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'cart_db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'secret'
    ports:
      - '5431:5432'
  payment:
    image: 'payment_app:latest'
    container_name: 'payment'
    depends_on:
      - 'payment_db'
    ports:
      - '8082:8082'
    environment:
      spring_datasource_url: 'jdbc:postgresql://payment_db:5432/payment_db'
      spring_datasource_username: 'root'
      spring_datasource_password: 'secret'
      spring_datasource_driver-class-name: 'org.postgresql.Driver'
      spring_jpa_properties_hibernate_dialect: 'org.hibernate.dialect.PostgreSQLDialect'
      spring_jpa_hibernate_ddl-auto: 'create-drop'
      spring_jpa_defer-datasource-initialization: 'true'
      spring_sql_init_mode: 'always'
  payment_db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'payment_db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'secret'
    ports:
      - '5432:5432'
  user:
    image: 'user_app:latest'
    container_name: 'user'
    depends_on:
      - 'user_db'
    ports:
      - '8083:8083'
    environment:
      spring_datasource_url: 'jdbc:postgresql://user_db:5432/user_db'
      spring_datasource_username: 'root'
      spring_datasource_password: 'secret'
      spring_datasource_driver-class-name: 'org.postgresql.Driver'
      spring_jpa_properties_hibernate_dialect: 'org.hibernate.dialect.PostgreSQLDialect'
      spring_jpa_hibernate_ddl-auto: 'create-drop'
      spring_jpa_defer-datasource-initialization: 'true'
      spring_sql_init_mode: 'always'
  user_db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'user_db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'secret'
    ports:
      - '5433:5432'